### ISSUE TITLE
Trying to get this to work with the Crusher from Silents Mod

### ISSUE THREAD

**Issue by CarlucciMods** [waylanderou/almost-all-the-ores#1]
![getting some ores to work](https://user-images.githubusercontent.com/31194015/71867766-8a076b80-30d9-11ea-801e-b9eab2f3e7b5.PNG)

**Comment by CarlucciMods** [comment]
so i thank you for getting back to me so fast. your mod has so much potential. Its a great mod. I since took it off my server as i don't like that it replaces any and all vanilla ores and modded ores. 

If you can somehow make the mod generate its own ores along side modded and vanilla ores without interfering with them and keep your ore generation separate from again the modded and vanilla ores, this mod would suit me and many others. If this is all possible now, let me know what I'm doing wrong, because i cant achieve this. I don't want your ores to replace the existing ores we have. I want vanilla ores such as coal and iron to generate as it normally would and then have your ores which gives us the option to increase our quantity.....making the game more extensive and fun and less grinding.

**Comment by waylanderou** [comment]
It is actually possible to achieve what you want, although it may be not clear when reading config options description (I am not an English native speaker).
Just change these options:

_hookAll_ = false  -> won't interfere with other mods.
_hookVanillaOnly_ = false  -> won't interfere with vanilla.

The only problem with that is: you won't be able to tune the spawning of vanilla stuff...
I should probably modify the whole generation system to meet all users need and to make things clearer in config. To be honest I had to check my code again to be sure what these options are really doing... When I have time, I will do this and release an update with more config options and everything clearer.

This is what underground looks like when setup like I previously said:
![image](https://user-images.githubusercontent.com/55812977/71974939-1bc6c400-3213-11ea-8b17-19b7643e75c1.png)

EDIT: I will probably release today the new version easier to setup. If not, tomorrow. It will sadly make previous config files unusable, but I think it's for the best.

**Comment by waylanderou** [comment]
Just released an update for both 1.14.4 and 1.15.1.

In short:
Vanilla generation can be set up in the vanilla section, including the spawning of iron and coal.
AatO generation can be disabled completely or not.
Other mods generation can be disabled or not.

I removed all those obscure options hookVanillaOnly, hookAll, ... 
Vanilla is now handled by the mod whether the user wants it or not, so everything needs to be set up in the vanilla config section if you so desire (activate coal ore, iron ore, ...).

**Comment by CarlucciMods** [comment]
Great work ! Def. much much better. a few sugestions. all ores in your game not matter loaded ore not loaded should be able to crush into 2x dust format. SO please makea dust version of each and maybe work with Silence to get them working together. this dust should also be able to smelt into his eletric furnace into ingots, onces thats done...we should be good and your mod will have support for any future mod or updates. GREAT WORK !

**Comment by waylanderou** [comment]
I am not going to make dust for all ores as only iron ores have (because they need it) this workaround with the refined dust. _Every other ore_ is properly tagged to be compatible with other mods since they don't interfere with the stone age feature.
I just tested a few ores with Silent's crusher and it works:
![image](https://user-images.githubusercontent.com/55812977/72008060-518b9d00-3253-11ea-90a8-11bb950b82d9.png)

I'm going to release a small patch later on (in a few days probably, but there's no hurry) to add a few crushing recipes for iron ores, just in case people don't know about the workaround. Not sure what more I could do :)

**Comment by CarlucciMods** [comment]
maybe make a device that breaks down the rock to make a dust or chunk so we can put into any furnace to make ingots. for all your ores. I have them all loaded even if some have no use, its still fun to have a collection or ores, dust, chunks and ingots.

**Comment by waylanderou** [comment]
Well I'll see about that. In the past I thought about adding rare earth elements to the game using the same refiner that's actually only used for the stone age feature. I didn't do it because then I thought it wouldn't add much to the gameplay...
I will reconsider adding this and more in the next few weeks (or even months, who knows). It takes more time than simply changing config because I need to do some research, to think, and finally to put everything into code, and maybe also make some textures.

**Comment by CarlucciMods** [comment]
I think you come along way and you have great work in front of you. That said, the question now remains, how far can you push your skills and talents. I will be ready to see what you come out with.
