### ISSUE TITLE
Missing/wrong ore tags

### ISSUE THREAD

**Issue by Akjosch** [waylanderou/almost-all-the-ores#10]
No, I don't mean forge:ores/iron - I see that it was a deliberate decision.

Pyrite and Sulphur (block) don't have `forge:ores/sulfur` and `forge:ores/sulphur`.

Lignite doesn't have `forge:ores/coal`.

Graphite has `forge:ores/graphite` instead of `forge:ores/coal`.

Stibnite has `forge:ores/stibnite` instead of `forge:ores/antimony`.

Calcite, Anhydrite and Gypsum don't have `forge:ores/calcium`, despite anhydrite (which is just dry gypsum, really) having the tooltip of being a source of calcium.

The platinum group blocks, Bastnasite variants, Monazite variants, Samarskite and Thortveitite aren't tagged with the elements they are ores of; though I see how it could lead to other mods misapplying them.

On a "it would be nice if ..." note, there are a few ores which can be sources of multiple elements - like ilmenite for iron and titanium - and it would be nice if they were tagged with all of them.

**Comment by waylanderou** [comment]
Sulphur block drops sulphur dust, so I decided to tag the latter as forge:ores/sulphur and also as sulfur in case mod developpers use that spelling (most likely).
There is two recipes to get sulphur dust from pyrite. [One](https://github.com/waylanderou/almost-all-the-ores/blob/1.15.1/src/main/resources/data/almostalltheores/recipes/sulphur_from_pyrite.json) using a crafting table, when the stone age option is disabled. When you play with that option, you can get sulphur dust by [putting ](https://github.com/waylanderou/almost-all-the-ores/blob/1.15.1/src/main/resources/data/almostalltheores/recipes/sulphur_from_pyrite_stoneage.json)pyrite into the refiner.
I do not really remember why I did not tag lignite as coal 🤔, therefore I am adding it to all coal tags, as well as graphite and jet. I am still keeping a graphite tag, since it can be useful for other mod developpers.
I completely forgot to create a calcium tag ! I will fix that.

Regarding platinum-group metals blocks and rare-earth elements blocks, I chose to tag their drops (platinum, palladium, ...) or refinement products (samarium, neodymium, ...). I thought it made more sense than registering multiple tags for the blocks. What do you think ?

Your last suggestion is interesting. I will take some time to think about new tags and add them.

Thank you for taking the time to report those few inconsistencies and giving suggestions.

**Comment by waylanderou** [comment]
First, sorry for getting back to this issue so late. 
I remembered why I did not add multiple tags on one ore. 
Imagine a block has 2 tags : forge:ores/titanium and forge:ores/iron. No problem so far. Imagine now you have a mod that adds a crusher machine with generic recipes using tags for its input. What will happen if you insert the block into the crusher ? Will it produce crushed iron or crushed titanium ? I do not know.
Adding multiple tags could produce unexpected behaviour so I will not add more.

These are the changes related to tags I made so far : 

fixed chromite tag (chromium)
fixed stibnite tag (antimony)
added calcium tag (calcite, gypsum, anhydrite)
added lignite, graphite and jet to minecraft and forge coal tags
