### ISSUE TITLE
Suggestion: remove unusable crafting recipes from the recipe book

### ISSUE THREAD

**Issue by nepphhh** [waylanderou/almost-all-the-ores#15]
Hi there. If you turn ores off (e.g., by disabling all non-vanilla ores as to use it for vanilla ore control) you still have a million dust recipes visible in your recipe book. This is confusing for my users & cluttery. Could they be removed if not usable (due to configuration settings)?

**Comment by waylanderou** [comment]
Could you possibly provide a screenshot ? I just checked and vanilla recipe book doesn't show REE dusts. If you mean Just Enough Items panel, you can hide everything related to AATO. There's already a config option for that. The option is called _hideEverythingInJEI_ (general section)

**Comment by nepphhh** [comment]
![2020-07-31_11 29 49](https://user-images.githubusercontent.com/4913409/89050707-2b2d6c00-d321-11ea-9d70-0b20acede741.png)

No problem; thanks for the response. How to reproduce: Make a survival world with all crafting recipes unlocked from the start (I use Quark for that, but there are other utilities, most named something like "I'm Not An Idiot").

**Comment by waylanderou** [comment]
To be honest, I have never used vanilla recipe book, and I think most people playing modded Minecraft haven't either, because JEI is just easier to use. I have no clue how to hide recipes from vanilla recipes book, even more after Quark has unlocked everything. Since I don't want to look into that further than I already have, I'm closing this. People will use JEI.
