### ISSUE TITLE
crashes at start

### ISSUE THREAD

**Issue by Warbringer12** [waylanderou/almost-all-the-ores#3]
[latest.log](https://github.com/waylanderou/almost-all-the-ores/files/4310047/latest.log)

**Comment by waylanderou** [comment]
Could you give more information ? Config options and AatO version

**Comment by Warbringer12** [comment]
AatO version:2.2.0.1
config is default

**Comment by waylanderou** [comment]
Thanks. Could you either send me the list of mods installed so I can test it myself, or just try this dev build and tell me if that solves the problem ? It seems to be a problem caused by whatever ores your mods adds, and also by me not coding properly the feature check.
The .jar is inside the archive because for some reason github doesn't support .jar uploads.
[dev-build.zip](https://github.com/waylanderou/almost-all-the-ores/files/4315316/dev-build.zip)

A little side note : while trying to fix this bug, I found another bug (small this time) in ore generation class, so I fixed it.

**Comment by Warbringer12** [comment]
the dev build you sent me seems to have fixed the issue that i was having

**Comment by waylanderou** [comment]
Nice. I will release an update next week hopefully for both 1.14 and 1.15 versions.
