### ISSUE TITLE
After updating to New version

### ISSUE THREAD

**Issue by BedrockLegends** [waylanderou/almost-all-the-ores#5]
Nether Quartz ore still Gens in nether with 	#Should Nether be cleared of all ore generation from vanilla and other mods.
	clearNether = true

**Comment by waylanderou** [comment]
Thank you for reporting that bug. 
After looking at the code, it turns out nether quartz ore is an underground decoration and not and underground ore. That's why it still generates even though there is no other ore.
That's an easy fix. I will release it in the next version of AatO with a few other improvements, hopefully in a day or two.

**Comment by BedrockLegends** [comment]
Thanks you again @waylanderou for the quick fix

**Comment by waylanderou** [comment]
I'm afraid the fix will take a bit longer than expected, as it is related to #4 and #3. I thought latest updated fixed those bugs, but it's not the case at all.

**Comment by waylanderou** [comment]
Update released.
